# Make sure to check out the wiki and given resource pack / config for help!
Furniture:
   example:
    item-name: 'Example Furniture'
    width: 1
    length: 1
    height: 1
    item-model: 'minecraft:feather'
    custom-model-data: 0
    rarity: rare
    chair:
      enabled: false
      y-offset: 0
    full-rotate: true
    commands:
      right-click: {}
      block-place: {}
      block-break: {}

Options:
    check-place-permissions: true
    check-break-permissions: true
