name: FurnitureEngine
version: @project.version@
main: com.mira.furnitureengine.FurnitureEngine
loader: com.mira.furnitureengine.FurnitureEngineLoader
authors:
  - Jim (AnEnragedPigeon)
  - Mira
api-version: '1.21.1'
description: Custom usable furniture items
load: STARTUP

dependencies:
  server:
    WorldGuard:
      load: AFTER
      required: false
    PlotSquared:
      load: AFTER
      required: false
    GriefPrevention:
      load: AFTER
      required: false
    GSit:
      load: AFTER
      required: false
    CreativeItemFilter:
      load: AFTER
      required: false
    CustomItems:
      load: AFTER
      required: false

permissions:
  furnitureengine.give:
   default: op
  furnitureengine.get:
   default: op
  furnitureengine.blockbreak:
   default: true
  furnitureengine.blockplace:
   default: true
  furnitureengine.admin:
   default: op
   children:
     furnitureengine.give: true
     furnitureengine.get: true
     furnitureengine.blockbreak: true
     furnitureengine.blockplace: true
  furnitureengine.*:
   default: op
   children:
     furnitureengine.admin: true