name: FurnitureEngine
version: @project.version@
main: com.mira.furnitureengine.FurnitureEngine
author: Mira
api-version: 1.19
description: Allows you to make custom usable furniture.
depend: []
softdepend:
  - WorldGuard
  - PlotSquared
  - GriefPrevention
  - GSit

commands:
  furnitureengine:
   description: Main Plugin command.
   aliases: [fe, furniture]
   permission: furnitureengine.basic

permissions:
  furnitureengine.give:
   default: op
  furnitureengine.get:
   default: op
  furnitureengine.blockbreak:
   default: true
  furnitureengine.blockplace:
   default: true
  furnitureengine.admin:
   default: op
   children:
     furnitureengine.give: true
     furnitureengine.get: true
     furnitureengine.blockbreak: true
     furnitureengine.blockplace: true
  furnitureengine.*:
   default: op
   children:
     furnitureengine.admin: true