[versions]
pluginYmlPaper = "0.8.0"
paperApi = "1.21.10-R0.1-SNAPSHOT"
worldguard = "7.0.14"
intellectualsitesBom = "1.52"
griefPrevention = "17.0.0"
gsit = "2.4.4"
creativeItemFilter = "3.0-SNAPSHOT"
customItemsApi = "1.0-SNAPSHOT"
messagesHelper = "1.1-SNAPSHOT"

[libraries]
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paperApi" }
worldguard = { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version.ref = "worldguard" }
plotsquaredCore = { group = "com.intellectualsites.plotsquared", name = "plotsquared-core" }
plotsquaredBukkit = { group = "com.intellectualsites.plotsquared", name = "plotsquared-bukkit" }
intellectualsitesBom = { group = "com.intellectualsites.bom", name = "bom-newest", version.ref = "intellectualsitesBom" }
griefPrevention = { group = "com.github.TechFortress", name = "GriefPrevention", version.ref = "griefPrevention" }
gsit = { group = "com.github.Gecolay.GSit", name = "core", version.ref = "gsit" }
creativeItemFilter = { group = "org.hurricanegames", name = "CreativeItemFilter", version.ref = "creativeItemFilter" }
customItemsApi = { group = "uk.co.notnull", name = "CustomItemsAPI", version.ref = "customItemsApi" }
messagesHelper = { group = "uk.co.notnull", name = "MessagesHelper-paper", version.ref = "messagesHelper" }

[plugins]
pluginYmlPaper = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginYmlPaper" }